// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXv9IBIVxHM3y-TrzvjKn-HwfUXyKr4PU',
    appId: '1:313283597917:web:4e97f04dfb99cba6a71fb4',
    messagingSenderId: '313283597917',
    projectId: 'feedback-form-84d9c',
    authDomain: 'feedback-form-84d9c.firebaseapp.com',
    storageBucket: 'feedback-form-84d9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_3OLcNpmhHuH3IU3iDk4Sthx2ZV4fKcY',
    appId: '1:313283597917:android:d4f012156784c816a71fb4',
    messagingSenderId: '313283597917',
    projectId: 'feedback-form-84d9c',
    storageBucket: 'feedback-form-84d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg63dmkKFF4PJyruHi6nGKAze9bR9dNzI',
    appId: '1:313283597917:ios:c645f0a04be6bdfca71fb4',
    messagingSenderId: '313283597917',
    projectId: 'feedback-form-84d9c',
    storageBucket: 'feedback-form-84d9c.appspot.com',
    iosClientId: '313283597917-9qfo3n1m9u1cqfp8cj1qtsemp4j5rsam.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFeedback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg63dmkKFF4PJyruHi6nGKAze9bR9dNzI',
    appId: '1:313283597917:ios:c645f0a04be6bdfca71fb4',
    messagingSenderId: '313283597917',
    projectId: 'feedback-form-84d9c',
    storageBucket: 'feedback-form-84d9c.appspot.com',
    iosClientId: '313283597917-9qfo3n1m9u1cqfp8cj1qtsemp4j5rsam.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFeedback',
  );
}
